openapi: 3.0.0

info:
  version: '1.0'
title: 'API de Ejemplo'
  description: 'Aprendiendo OpenAPI (By Lucas)'

servers:
  - url: https://dev.foo.com/v1
    description: Development Server
    
  - url: https://prod.foo.com/v1
    description: Production Server

paths:
  /empleados:
    get:
      description: Obtener lista detallada de empleados
      parameters:
        - name: bodyLimit
          in: query
          description: Cantidad de empleados a devolver por pagina
          schema:
            type: integer
            minimum: 5
            maximum: 50
            example: 10
        - name: pageLimit
          in: query
          description: Cantidad de paginas de empleados a devolver
          schema:
            type: integer
            minimum: 1
            maximum: 5
            example: 2
      responses:
        200:
          description: Empleados devueltos con exito
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Empleados'

    post:
      description: Crear un nuevo empleado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Empleado'
      responses:
        200:
          description: Empleado creado con exito
        500:
          description: Error al crear empleado
          
  /empleado/{id}:
    get:
      description: Obtener informacion acerca de un empleado en particular
      parameters:
        - in: path
          name: id
          required: true
          description: ID del empleado
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Empleado encontrado y devuelto con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empleado'
            application/xml:
              schema:
                $ref: '#/components/schemas/Empleado'
            
components:
  schemas:
    Empleado:
      description: Modelo de empleado
      type: object
      properties:
        id: 
          type: integer
          example: 1
        nombre:
          type: string
          example: Lucas
        apellido:
          type: string
          example: Maspero
        puesto:
          type: string
          example: Desarrollador
    Empleados:
      description: Modelo de empleados (arreglo)
      type: array
      items:
        $ref: '#/components/schemas/Empleado'