# Step 1: Install Node Packages
FROM node:12 AS npm-i
WORKDIR /.
COPY package*.json ./
RUN npm install
RUN npm install @openapitools/openapi-generator-cli -g
COPY . .


# Step 2: Validate Specification File
FROM npm-i AS validate
RUN npm run validate-spec

# Step 3: Generate .NET Core API Service Stubs
#docker run --rm \
#  -v ${PWD}:/local openapitools/openapi-generator-cli generate \
#  -i /local/petstore.yaml \
#  -g go \
#  -o /local/out/go

FROM openapitools/openapi-generator-cli AS generate-service-dotnetcore
WORKDIR /.
RUN openapi-generator-cli generate -g aspnetcore -i Specification/security-api-specification.yaml -o .\\Output\\SecurityService\\NetCore --additional-properties=aspnetCoreVersion=3.1,generateBody=false,classModifier=abstract,operationModifier=abstract,operationResultTask=true,useFrameworkReference=false,useSwashbuckle=false

# Step 4: Build .NET Core API Service Stubs

# Step X: Run Documentation UI
#FROM validate AS run-documentation
#EXPOSE 8080
#CMD ["npm", "run", "documentation"]