# Node & Java Base
FROM timbru31/java-node

# Arguments
ARG BUILD_COUNTER
ARG NUGET_FEED_API_KEY
ARG NUGET_FEED

# Initialize
WORKDIR /.
COPY . .

# Step 1: Install Node Packages
RUN npm install

# Step 2: Validate Specification File
RUN npm run validate-spec

# Step 3: Get Build Parameters
RUN npm run parse-spec

# Step 4: Generate .NET Core API Service Stubs (Using Previous Build Parameters)
RUN export API_MAJOR_VERSION=$(cat /Output/BuildParameters/ApiMajorVersion) \
    && export API_MINOR_VERSION=$(cat /Output/BuildParameters/ApiMinorVersion) \
    && npm run generate-service-dotnetcore -- --additional-properties=packageVersion=${API_MAJOR_VERSION}.${API_MINOR_VERSION}.${BUILD_COUNTER}

# DotNet Base
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

# Copying files between stages
COPY --from=0 . .   

# Specifying NuGet Id
WORKDIR /Output/SecurityService/NetCore/src/Org.OpenAPITools
RUN sed -i 's/\$id\$/PPA.FIP.Security.Specification/' Org.OpenAPITools.nuspec

# Step 5: Build .NET Core API Service Stubs
RUN dotnet build

# Step 6: Create NuGet Package from Service Stubs
RUN dotnet pack -p:NuspecFile=Org.OpenAPITools.nuspec -o nupkgs

# Step 7: Publish NuGet Package
RUN echo "${NUGET_FEED}"
RUN echo "${NUGET_FEED_API_KEY}"

RUN dotnet nuget push nupkgs/PPA.FIP.Security.Specification.25.7.9.nupkg --api-key $NUGET_FEED_API_KEY --source $NUGET_FEED