# Step 1: Install Node Packages
FROM node:12 AS npm-i
WORKDIR /.
COPY package*.json ./
RUN npm install
RUN npm install @openapitools/openapi-generator-cli -g
COPY . .


# Step 2: Validate Specification File
FROM npm-i AS validate
RUN npm run validate-spec

# Step 3: Generate .NET Core API Service Stubs
FROM validate AS generate-service-dotnetcore
RUN npm run generate-service-dotnetcore

# Step 4: Build .NET Core API Service Stubs

# Step X: Run Documentation UI
#FROM validate AS run-documentation
#EXPOSE 8080
#CMD ["npm", "run", "documentation"]